//<#!@READ-ONLY-SECTION-START@!#>
/*!
 * \brief Intel(R) CoFluent(TM) Studio - Intel Corporation
 * \details Simulation model of chi_icn_plf_packupPlf generated by C++ Generator for SystemC/TLM2
 */
#ifndef COFS_MODEL_CHI_ICN_PLF_PACKUPPLF_CHI_ICN_PLF_PACKUPPLF_TOP_MODEL
#define COFS_MODEL_CHI_ICN_PLF_PACKUPPLF_CHI_ICN_PLF_PACKUPPLF_TOP_MODEL

/// Top Header includes start
//Executable platform model
#include "cfm_chi_icn_plf_packupplf.h"
/// Top Header includes end

#endif // COFS_MODEL_CHI_ICN_PLF_PACKUPPLF_CHI_ICN_PLF_PACKUPPLF_TOP_MODEL

//<#!@READ-ONLY-SECTION-END@!#>