//<#!@READ-ONLY-SECTION-START@!#>
/*!
 * \class cfm_chi_icn_plf_packupplf
 * \brief Intel(R) CoFluent(TM) Studio - Intel Corporation
 * \details Simulation model of chi_icn_plf_packupPlf generated by C++ Generator for SystemC/TLM2
 */

#ifndef COFS_MODEL_CHI_ICN_PLF_PACKUPPLF_CHI_ICN_PLF_PACKUPPLF
#define COFS_MODEL_CHI_ICN_PLF_PACKUPPLF_CHI_ICN_PLF_PACKUPPLF

/// Model Header includes start
#include <vector>

#include "cfm_chi_icn_plf_packupplf_global.h"
#include "cfm_chi_icn_plf_packupplf_global_types.h"
#include "cofluent.h"

#include "cfm_chi_icn.h"
#include "cfm_mem_sn.h"
#include "cfm_tg_rnf.h"

//<#!@READ-ONLY-SECTION-END@!#>
//Start of 'chi_icn_plf_packupPlf includes' algorithm generated code

//End of 'chi_icn_plf_packupPlf includes' algorithm generated code
//<#!@READ-ONLY-SECTION-START@!#>
/// Model Header includes end

///    \defgroup dxgchi_icn_plf_packupPlf Function chi_icn_plf_packupPlf
//@{
///        \page dxpchi_icn_plf_packupPlf
//@{
///    \brief chi_icn_plf_packupPlf function model start
class cfm_chi_icn_plf_packupplf: public cf_core::cf_platform {
public:
	/// cfm_chi_icn_plf_packupplf type define start
	/// relations typedef

	/// cfm_chi_icn_plf_packupplf type define end

	/// constructor
	cfm_chi_icn_plf_packupplf(sc_core::sc_module_name name);

	/// destructor
	virtual ~cfm_chi_icn_plf_packupplf(void);
	virtual void cb_before_elaboration(void);

public:
	/// \name components
	//@{
	cfm_mem_sn* mem_sn;
	std::vector<cfm_tg_rnf*> tg_rnf_vec;
	//@}

protected:
	/// initialize attributes
	void cb_init_attributes(void);
	/// initialize definitions
	void cb_init_local_vars(void);

public:
	/// \name relations
	//@{
	cfm_chi_icn bus_CHI_ICN;
	//@}

	/// Model private fields start
	/// Model private fields end

	/// \name user-defined local declarations
	//<#!@READ-ONLY-SECTION-END@!#>
	//Start of 'chi_icn_plf_packupPlf local declarations' algorithm generated code

	//End of 'chi_icn_plf_packupPlf local declarations' algorithm generated code
	//<#!@READ-ONLY-SECTION-START@!#>

};
///    \brief chi_icn_plf_packupPlf function model end

//@}
//@}
#endif // COFS_MODEL_CHI_ICN_PLF_PACKUPPLF_CHI_ICN_PLF_PACKUPPLF

//<#!@READ-ONLY-SECTION-END@!#>