//<#!@READ-ONLY-SECTION-START@!#>
/*!
 * \class cfm_tg_rnf
 * \brief Intel(R) CoFluent(TM) Studio - Intel Corporation
 * \details Simulation model of chi_icn_plf_packupPlf generated by C++ Generator for SystemC/TLM2
 */

#ifndef COFS_MODEL_CHI_ICN_PLF_PACKUPPLF_TG_RNF
#define COFS_MODEL_CHI_ICN_PLF_PACKUPPLF_TG_RNF

/// Model Header includes start

#include "cfm_chi_icn_plf_packupplf_global.h"
#include "cfm_chi_icn_plf_packupplf_global_types.h"
#include "cofluent.h"

/*Start of 'Inherited classes header' from tg_rnf's model property generated code*/
#include "rnf_subsys.h"
/*End of 'Inherited classes header' from tg_rnf's model property generated code*/
//<#!@READ-ONLY-SECTION-END@!#>
//Start of 'tg_rnf includes' algorithm generated code
//End of 'tg_rnf includes' algorithm generated code
//<#!@READ-ONLY-SECTION-START@!#>
#include "cfm_tg_rnf_mi.h"
/// Model Header includes end

///    \defgroup dxgtg_rnf Function tg_rnf
//@{
///        \page dxptg_rnf
//@{
///    \brief tg_rnf function model start
class cfm_tg_rnf:
/*Start of 'Inherited classes declaration' from tg_rnf's property generated code*/
public rnf_subsys
/*End of 'Inherited classes declaration' from tg_rnf's property generated code*/
{
public:
	/// cfm_tg_rnf type define start

	/// ports typedef
	//typedef tlm_utils::multi_passthrough_initiator_socket<cf_core::cf_itc_b> p_bus_CHI_ICN_t;
	/// cfm_tg_rnf type define end

	/// constructor
	cfm_tg_rnf(sc_core::sc_module_name name);

	/// destructor
	virtual ~cfm_tg_rnf(void);
	virtual void cb_before_elaboration(void);

public:
	/// \name input/output ports
	//@{

public:
	/// \name components
	//@{
	//@}

	/// after active callback
	void itc_proc_tg_rnf_cb_after_active(void);

	/// after inactive callback
	void itc_proc_tg_rnf_cb_after_inactive(void);

protected:
	/// initialize attributes
	void cb_init_attributes(void);
	/// initialize definitions
	void cb_init_local_vars(void);

	/// Model private fields start
	/// Model private fields end

	/// \name user-defined local declarations
	//<#!@READ-ONLY-SECTION-END@!#>
	//Start of 'tg_rnf local declarations' algorithm generated code

	//End of 'tg_rnf local declarations' algorithm generated code
	//<#!@READ-ONLY-SECTION-START@!#>

};
///    \brief tg_rnf function model end

//@}
//@}
#endif // COFS_MODEL_CHI_ICN_PLF_PACKUPPLF_TG_RNF

//<#!@READ-ONLY-SECTION-END@!#>