//<#!@READ-ONLY-SECTION-START@!#>
/*!
 * \class cfm_mem_sn
 * \brief Intel(R) CoFluent(TM) Studio - Intel Corporation
 * \details Simulation model of chi_icn_plf_packupPlf generated by C++ Generator for SystemC/TLM2
 */

#ifndef COFS_MODEL_CHI_ICN_PLF_PACKUPPLF_MEM_SN
#define COFS_MODEL_CHI_ICN_PLF_PACKUPPLF_MEM_SN

/// Model Header includes start

#include "cfm_chi_icn_plf_packupplf_global.h"
#include "cfm_chi_icn_plf_packupplf_global_types.h"
#include "cofluent.h"

/*Start of 'Inherited classes header' from mem_sn's model property generated code*/
#include "sn-chi.h"
/*End of 'Inherited classes header' from mem_sn's model property generated code*/
//<#!@READ-ONLY-SECTION-END@!#>
//Start of 'mem_sn includes' algorithm generated code
#define comma ,
//End of 'mem_sn includes' algorithm generated code
//<#!@READ-ONLY-SECTION-START@!#>
#include "cfm_mem_sn_si.h"
/// Model Header includes end

///    \defgroup dxgmem_sn Function mem_sn
//@{
///        \page dxpmem_sn
//@{
///    \brief mem_sn function model start
class cfm_mem_sn:
/*Start of 'Inherited classes declaration' from mem_sn's property generated code*/
public SlaveNode_F<10 comma 20>
/*End of 'Inherited classes declaration' from mem_sn's property generated code*/
{
public:
	/// cfm_mem_sn type define start

	/// ports typedef
	//typedef tlm_utils::multi_passthrough_target_socket<cf_core::cf_itc_b> p_bus_CHI_ICN_t;
	/// cfm_mem_sn type define end

	/// constructor
	cfm_mem_sn(sc_core::sc_module_name name);

	/// destructor
	virtual ~cfm_mem_sn(void);
	virtual void cb_before_elaboration(void);

public:
	/// \name input/output ports
	//@{

public:
	/// \name components
	//@{
	//@}

	/// after active callback
	void itc_proc_mem_sn_cb_after_active(void);

	/// after inactive callback
	void itc_proc_mem_sn_cb_after_inactive(void);

protected:
	/// initialize attributes
	void cb_init_attributes(void);
	/// initialize definitions
	void cb_init_local_vars(void);

	/// Model private fields start
	/// Model private fields end

	/// \name user-defined local declarations
	//<#!@READ-ONLY-SECTION-END@!#>
	//Start of 'mem_sn local declarations' algorithm generated code

	//End of 'mem_sn local declarations' algorithm generated code
	//<#!@READ-ONLY-SECTION-START@!#>

};
///    \brief mem_sn function model end

//@}
//@}
#endif // COFS_MODEL_CHI_ICN_PLF_PACKUPPLF_MEM_SN

//<#!@READ-ONLY-SECTION-END@!#>