//<#!@READ-ONLY-SECTION-START@!#>
/*!
 * \brief Intel(R) CoFluent(TM) Studio - Intel Corporation
 * \details Simulation model of chi_icn_SysSys generated by C++ Generator for SystemC/TLM2
 */
#ifndef COFS_MODEL_CHI_ICN_SYSSYS_CHI_ICN_SYSSYS_TOP_MODEL
#define COFS_MODEL_CHI_ICN_SYSSYS_CHI_ICN_SYSSYS_TOP_MODEL

/// Top Header includes start
#include "cfm_chi_icn_syssys.h"
/// Top Header includes end

#endif // COFS_MODEL_CHI_ICN_SYSSYS_CHI_ICN_SYSSYS_TOP_MODEL

//<#!@READ-ONLY-SECTION-END@!#>