//<#!@READ-ONLY-SECTION-START@!#>
/*!
 * \class cfm_connector_st2
 * \brief Intel(R) CoFluent(TM) Studio - Intel Corporation
 * \details Simulation model of chi_icn_SysSys generated by C++ Generator for SystemC/TLM2
 */

#ifndef COFS_MODEL_CHI_ICN_SYSSYS_CONNECTOR_ST2
#define COFS_MODEL_CHI_ICN_SYSSYS_CONNECTOR_ST2

#include "cofluent.h"
//<#!@READ-ONLY-SECTION-END@!#>
//Start of 'connector_st2 includes' algorithm generated code
#include "cfm_mem_tlm.h"
#include "cfm_sn_tlm.h"

#ifndef _EMPTY_H_
#define _EMPTY_H_
#include "empty.h"
#endif
//End of 'connector_st2 includes' algorithm generated code
//<#!@READ-ONLY-SECTION-START@!#>

///    \defgroup dxgconnector_st2 Function connector_st2
//@{
///        \page dxpconnector_st2
//@{
///    \brief connector_st2 function model.
class cfm_connector_st2:
/*Start of 'Inherited classes declaration' from connector_st2 property generated code*/
public empty
/*End of 'Inherited classes declaration' from connector_st2 property generated code*/
{
public:
	/// constructor
	cfm_connector_st2(sc_core::sc_module_name name);

	/// destructor
	virtual ~cfm_connector_st2(void);

	/// before arbitration callback
	void itc_bus_connector_st2_cb_before_arbitration(
			const tlm::tlm_generic_payload & _trans);

	/// after arbitration callback
	void itc_bus_connector_st2_cb_after_arbitration(
			const tlm::tlm_generic_payload & _trans);

	/// before transfer callback
	void itc_bus_connector_st2_cb_before_transfer(
			const tlm::tlm_generic_payload & _trans);

	/// after transfer callback
	void itc_bus_connector_st2_cb_after_transfer(
			const tlm::tlm_generic_payload & _trans);

protected:
	/// initialize definitions
	void cb_init_local_vars(void);

	/// \name user-defined local declarations
	//<#!@READ-ONLY-SECTION-END@!#>
	//Start of 'connector_st2 local declarations' algorithm generated code
public:
	void bind(cfm_mem_tlm* mem_tlm, cfm_sn_tlm* sn_tlm) {
		//sn_tlm->init_socket(mem_tlm->socket);
		(sn_tlm->init_socket).bind(mem_tlm->socket);
		cout << "connector_st2 bind done" << endl;
	}
	;
	//End of 'connector_st2 local declarations' algorithm generated code
	//<#!@READ-ONLY-SECTION-START@!#>

};

//@}
//@}
#endif // COFS_MODEL_CHI_ICN_SYSSYS_CONNECTOR_ST2

//<#!@READ-ONLY-SECTION-END@!#>