//<#!@READ-ONLY-SECTION-START@!#>
/// \mainpage chi_icn_sysSys
///
/// Source code generated by Intel CoFluent C++ Generator for SystemC/TLM2 for:
///
/// project: chi_icn_sysSys
///
/// \section dxsGlobals Globals
///
///    - \subpage dxpGlobals "Global declarations/initializations"
///
///    - \subpage dxpRelTypes "Relation Datatypes"
///
///    - \subpage dxpDPTypes "Design Parameter Types"
///
///    - \subpage dxpUserCallbacks "User-defined callback functions"
///
/// \section dxsModules Design modules
///
///    - \subpage dxpchi_icn_sysSys "Application chi_icn_sysSys"
///
///    - \subpage dxpchi_icn_sysSys "Function chi_icn_sysSys"
///
///    - \subpage dxptg_rnf_tlm "Function tg_rnf_tlm"
///
///    - \subpage dxprnf_tlm "Function rnf_tlm"
///
///    - \subpage dxpsn_tlm "Function sn_tlm"
///
///    - \subpage dxpsnf_tlm "Function snf_tlm"
///
///    - \subpage dxpmem_tlm "Function mem_tlm"
///
///
/// Intel(R) CoFluent(TM) Studio - Intel Corporation
/// Version: x.y.z Dev - Build id: x.y.z-dev
/// C++ Modeling Library for SystemC/TLM2 (SCL)
///

#ifndef COFS_MODEL_CHI_ICN_SYSSYS_CHI_ICN_SYSSYS_GLOBAL_DEFINITIONS
#define COFS_MODEL_CHI_ICN_SYSSYS_CHI_ICN_SYSSYS_GLOBAL_DEFINITIONS

/// global includes start
#include "cfm_chi_icn_syssys_global_types.h"
#include "cofluent.h"

/// global includes end
#ifndef COFS_MODEL_APPLICATION_LEVEL
#define COFS_MODEL_APPLICATION_LEVEL
#endif

/// \defgroup dxgGlobals global declarations
//@{
///		\page dxpGlobals
//@{
//<#!@READ-ONLY-SECTION-END@!#>
//Start of 'chi_icn_sysSys global declarations' algorithm generated code

//End of 'chi_icn_sysSys global declarations' algorithm generated code
//<#!@READ-ONLY-SECTION-START@!#>
//@}
//@}

#endif // COFS_MODEL_CHI_ICN_SYSSYS_CHI_ICN_SYSSYS_GLOBAL_DEFINITIONS

//<#!@READ-ONLY-SECTION-END@!#>