//<#!@READ-ONLY-SECTION-START@!#>
/*!
 * \class cfm_mem_tlm
 * \brief Intel(R) CoFluent(TM) Studio - Intel Corporation
 * \details Simulation model of chi_icn_sysSys generated by C++ Generator for SystemC/TLM2
 */

#ifndef COFS_MODEL_CHI_ICN_SYSSYS_MEM_TLM
#define COFS_MODEL_CHI_ICN_SYSSYS_MEM_TLM

/// Model Header includes start
#include "cfm_chi_icn_syssys_global.h"
#include "cfm_chi_icn_syssys_global_types.h"
#include "cofluent.h"

/*Start of 'Inherited classes header' from mem_tlm's model property generated code*/
#include "memory.h"
/*End of 'Inherited classes header' from mem_tlm's model property generated code*/
//<#!@READ-ONLY-SECTION-END@!#>
//Start of 'mem_tlm includes' algorithm generated code
//End of 'mem_tlm includes' algorithm generated code
//<#!@READ-ONLY-SECTION-START@!#>
/// Model Header includes end
///    \defgroup dxgmem_tlm Function mem_tlm
//@{
///        \page dxpmem_tlm
//@{
///    \brief mem_tlm function model start
class cfm_mem_tlm:
/*Start of 'Inherited classes declaration' from mem_tlm's property generated code*/
public memory
/*End of 'Inherited classes declaration' from mem_tlm's property generated code*/
{
public:
	/// cfm_mem_tlm type define start

	/// ports typedef
	typedef tlm_utils::multi_passthrough_initiator_socket<cf_core::cf_itc_b> p_bus_connector_st_t;
	/// cfm_mem_tlm type define end

	/// constructor
	cfm_mem_tlm(sc_core::sc_module_name name);

	/// destructor
	virtual ~cfm_mem_tlm(void);
	virtual void cb_before_elaboration(void);

public:
	/// \name input/output ports
	//@{
	//@}

	/// after active callback
	void itc_proc_mem_tlm_cb_after_active(void);

	/// after inactive callback
	void itc_proc_mem_tlm_cb_after_inactive(void);

protected:
	/// initialize attributes
	void cb_init_attributes(void);
	/// initialize definitions
	void cb_init_local_vars(void);

	/// Model private fields start
	/// Model private fields end

	/// \name user-defined local declarations
	//<#!@READ-ONLY-SECTION-END@!#>
	//Start of 'mem_tlm local declarations' algorithm generated code

	//End of 'mem_tlm local declarations' algorithm generated code
	//<#!@READ-ONLY-SECTION-START@!#>

};
///    \brief mem_tlm function model end

//@}
//@}
#endif // COFS_MODEL_CHI_ICN_SYSSYS_MEM_TLM

//<#!@READ-ONLY-SECTION-END@!#>