//<#!@READ-ONLY-SECTION-START@!#>
/*!
 * \class cfm_riscv_vp
 * \brief Intel(R) CoFluent(TM) Studio - Intel Corporation
 * \details Simulation model of chi_icn_SysSys generated by C++ Generator for SystemC/TLM2
 */

#ifndef COFS_MODEL_CHI_ICN_SYSSYS_RISCV_VP
#define COFS_MODEL_CHI_ICN_SYSSYS_RISCV_VP

/// Model Header includes start
#include "cfm_chi_icn_syssys_global.h"
#include "cfm_chi_icn_syssys_global_types.h"
#include "cofluent.h"

/*Start of 'Inherited classes header' from riscv_vp's model property generated code*/
#include "riscv_vp_adapter_wrapper.h"
/*End of 'Inherited classes header' from riscv_vp's model property generated code*/
//<#!@READ-ONLY-SECTION-END@!#>
//Start of 'riscv_vp includes' algorithm generated code
//End of 'riscv_vp includes' algorithm generated code
//<#!@READ-ONLY-SECTION-START@!#>
/// Model Header includes end
///    \defgroup dxgriscv_vp Function riscv_vp
//@{
///        \page dxpriscv_vp
//@{
///    \brief riscv_vp function model start
class cfm_riscv_vp:
/*Start of 'Inherited classes declaration' from riscv_vp's property generated code*/
public riscv_vp_adapter_wrapper
/*End of 'Inherited classes declaration' from riscv_vp's property generated code*/
{
public:
	/// cfm_riscv_vp type define start

	/// ports typedef
	typedef tlm_utils::multi_passthrough_initiator_socket<cf_core::cf_itc_b> p_bus_connector_st1_t;
	/// cfm_riscv_vp type define end

	/// constructor
	cfm_riscv_vp(sc_core::sc_module_name name);

	/// destructor
	virtual ~cfm_riscv_vp(void);
	virtual void cb_before_elaboration(void);

public:
	/// \name input/output ports
	//@{
	//@}

	/// after active callback
	void itc_proc_riscv_vp_cb_after_active(void);

	/// after inactive callback
	void itc_proc_riscv_vp_cb_after_inactive(void);

protected:
	/// initialize attributes
	void cb_init_attributes(void);
	/// initialize definitions
	void cb_init_local_vars(void);

	/// Model private fields start
	/// Model private fields end

	/// \name user-defined local declarations
	//<#!@READ-ONLY-SECTION-END@!#>
	//Start of 'riscv_vp local declarations' algorithm generated code

	//End of 'riscv_vp local declarations' algorithm generated code
	//<#!@READ-ONLY-SECTION-START@!#>

};
///    \brief riscv_vp function model end

//@}
//@}
#endif // COFS_MODEL_CHI_ICN_SYSSYS_RISCV_VP

//<#!@READ-ONLY-SECTION-END@!#>