//<#!@READ-ONLY-SECTION-START@!#>
/*!
 * \class cfm_tg_rnf_tlm
 * \brief Intel(R) CoFluent(TM) Studio - Intel Corporation
 * \details Simulation model of chi_icn_sysSys generated by C++ Generator for SystemC/TLM2
 */

#ifndef COFS_MODEL_CHI_ICN_SYSSYS_TG_RNF_TLM
#define COFS_MODEL_CHI_ICN_SYSSYS_TG_RNF_TLM

/// Model Header includes start
#include "cfm_chi_icn_syssys_global.h"
#include "cfm_chi_icn_syssys_global_types.h"
#include "cofluent.h"

/*Start of 'Inherited classes header' from tg_rnf_tlm's model property generated code*/
#include "rnf_subsys.h"
/*End of 'Inherited classes header' from tg_rnf_tlm's model property generated code*/
//<#!@READ-ONLY-SECTION-END@!#>
//Start of 'tg_rnf_tlm includes' algorithm generated code
//End of 'tg_rnf_tlm includes' algorithm generated code
//<#!@READ-ONLY-SECTION-START@!#>
#include "cfm_tg_rnf_tlm_rnf_tlm.h"
/// Model Header includes end

///    \defgroup dxgtg_rnf_tlm Function tg_rnf_tlm
//@{
///        \page dxptg_rnf_tlm
//@{
///    \brief tg_rnf_tlm function model start
class cfm_tg_rnf_tlm:
/*Start of 'Inherited classes declaration' from tg_rnf_tlm's property generated code*/
public rnf_subsys
/*End of 'Inherited classes declaration' from tg_rnf_tlm's property generated code*/
{
public:
	/// cfm_tg_rnf_tlm type define start

	/// ports typedef
	typedef tlm_utils::multi_passthrough_initiator_socket<cf_core::cf_itc_b> p_bus_CHI_ICN_TLM_t;
	/// cfm_tg_rnf_tlm type define end

	/// constructor
	cfm_tg_rnf_tlm(sc_core::sc_module_name name);

	/// destructor
	virtual ~cfm_tg_rnf_tlm(void);
	virtual void cb_before_elaboration(void);

public:
	/// \name input/output ports
	//@{
	//@}

public:
	/// \name components
	//@{
	cfm_tg_rnf_tlm_rnf_tlm* rnf_tlm;
	//@}

	/// after active callback
	void itc_proc_tg_rnf_tlm_cb_after_active(void);

	/// after inactive callback
	void itc_proc_tg_rnf_tlm_cb_after_inactive(void);

protected:
	/// initialize attributes
	void cb_init_attributes(void);
	/// initialize definitions
	void cb_init_local_vars(void);

	/// Model private fields start
	/// Model private fields end

	/// \name user-defined local declarations
	//<#!@READ-ONLY-SECTION-END@!#>
	//Start of 'tg_rnf_tlm local declarations' algorithm generated code

	//End of 'tg_rnf_tlm local declarations' algorithm generated code
	//<#!@READ-ONLY-SECTION-START@!#>

};
///    \brief tg_rnf_tlm function model end

//@}
//@}
#endif // COFS_MODEL_CHI_ICN_SYSSYS_TG_RNF_TLM

//<#!@READ-ONLY-SECTION-END@!#>