//<#!@READ-ONLY-SECTION-START@!#>
/*!
 * \class cfm_connector_st
 * \brief Intel(R) CoFluent(TM) Studio - Intel Corporation
 * \details Simulation model of chi_icn_sysSys generated by C++ Generator for SystemC/TLM2
 */

#ifndef COFS_MODEL_CHI_ICN_SYSSYS_CONNECTOR_ST
#define COFS_MODEL_CHI_ICN_SYSSYS_CONNECTOR_ST

#include "cofluent.h"
/*Start of 'Inherited classes header' from connector_st property generated code*/
#include "empty.h"
/*End of 'Inherited classes header' from connector_st property generated code*/
//<#!@READ-ONLY-SECTION-END@!#>
//Start of 'connector_st includes' algorithm generated code
#include "cfm_mem_tlm.h"
#include "cfm_sn_tlm.h"
//End of 'connector_st includes' algorithm generated code
//<#!@READ-ONLY-SECTION-START@!#>

///    \defgroup dxgconnector_st Function connector_st
//@{
///        \page dxpconnector_st
//@{
///    \brief connector_st function model.
class cfm_connector_st:
/*Start of 'Inherited classes declaration' from connector_st property generated code*/
public empty
/*End of 'Inherited classes declaration' from connector_st property generated code*/
{
public:
	/// constructor
	cfm_connector_st(sc_core::sc_module_name name);

	/// destructor
	virtual ~cfm_connector_st(void);

	/// before arbitration callback
	void itc_bus_connector_st_cb_before_arbitration(
			const tlm::tlm_generic_payload & _trans);

	/// after arbitration callback
	void itc_bus_connector_st_cb_after_arbitration(
			const tlm::tlm_generic_payload & _trans);

	/// before transfer callback
	void itc_bus_connector_st_cb_before_transfer(
			const tlm::tlm_generic_payload & _trans);

	/// after transfer callback
	void itc_bus_connector_st_cb_after_transfer(
			const tlm::tlm_generic_payload & _trans);

protected:
	/// initialize definitions
	void cb_init_local_vars(void);

	/// \name user-defined local declarations
	//<#!@READ-ONLY-SECTION-END@!#>
	//Start of 'connector_st local declarations' algorithm generated code

public:
	void bind(cfm_mem_tlm* mem_tlm, cfm_sn_tlm* sn_tlm) {
		//sn_tlm->init_socket(mem_tlm->socket);
		(sn_tlm->init_socket).bind(mem_tlm->socket);
		cout << "bind done" << endl;
	}
	;
	//End of 'connector_st local declarations' algorithm generated code
	//<#!@READ-ONLY-SECTION-START@!#>

};

//@}
//@}
#endif // COFS_MODEL_CHI_ICN_SYSSYS_CONNECTOR_ST

//<#!@READ-ONLY-SECTION-END@!#>