//<#!@READ-ONLY-SECTION-START@!#>
/*!
 * \class cfm_chi_icn_plfplf
 * \brief Intel(R) CoFluent(TM) Studio - Intel Corporation
 * \details Simulation model of chi_icn_PlfPlf generated by C++ Generator for SystemC/TLM2
 */

#ifndef COFS_MODEL_CHI_ICN_PLFPLF_CHI_ICN_PLFPLF
#define COFS_MODEL_CHI_ICN_PLFPLF_CHI_ICN_PLFPLF

/// Model Header includes start
#include <vector>

#include "cfm_chi_icn_plfplf_global.h"
#include "cfm_chi_icn_plfplf_global_types.h"
#include "cofluent.h"

#include "cfm_chi_icn.h"
#include "cfm_mem_sn.h"
#include "cfm_tg_rnf.h"

//<#!@READ-ONLY-SECTION-END@!#>
//Start of 'chi_icn_PlfPlf includes' algorithm generated code

//End of 'chi_icn_PlfPlf includes' algorithm generated code
//<#!@READ-ONLY-SECTION-START@!#>
/// Model Header includes end

///    \defgroup dxgchi_icn_PlfPlf Function chi_icn_PlfPlf
//@{
///        \page dxpchi_icn_PlfPlf
//@{
///    \brief chi_icn_PlfPlf function model start
class cfm_chi_icn_plfplf: public cf_core::cf_platform {
public:
	/// cfm_chi_icn_plfplf type define start
	/// relations typedef

	/// cfm_chi_icn_plfplf type define end

	/// constructor
	cfm_chi_icn_plfplf(sc_core::sc_module_name name);

	/// destructor
	virtual ~cfm_chi_icn_plfplf(void);
	virtual void cb_before_elaboration(void);

public:
	/// \name components
	//@{
	cfm_mem_sn* mem_sn;
	std::vector<cfm_tg_rnf*> tg_rnf_vec;
	//@}

protected:
	/// initialize attributes
	void cb_init_attributes(void);
	/// initialize definitions
	void cb_init_local_vars(void);

public:
	/// \name relations
	//@{
	cfm_chi_icn bus_CHI_ICN;
	//@}

	/// Model private fields start
	/// Model private fields end

	/// \name user-defined local declarations
	//<#!@READ-ONLY-SECTION-END@!#>
	//Start of 'chi_icn_PlfPlf local declarations' algorithm generated code

	//End of 'chi_icn_PlfPlf local declarations' algorithm generated code
	//<#!@READ-ONLY-SECTION-START@!#>

};
///    \brief chi_icn_PlfPlf function model end

//@}
//@}
#endif // COFS_MODEL_CHI_ICN_PLFPLF_CHI_ICN_PLFPLF

//<#!@READ-ONLY-SECTION-END@!#>