//<#!@READ-ONLY-SECTION-START@!#>
/*!
 * \brief Intel(R) CoFluent(TM) Studio - Intel Corporation
 * \details Simulation model of chi_icn_PlfPlf generated by C++ Generator for SystemC/TLM2
 */

#ifndef COFS_MODEL_CHI_ICN_PLFPLF_CHI_ICN_PLFPLF_GLOBAL_TYPE_DEFINITIONS
#define COFS_MODEL_CHI_ICN_PLFPLF_CHI_ICN_PLFPLF_GLOBAL_TYPE_DEFINITIONS

/// global types includes start

#include "cofluent.h"
/// global types includes end
/// \addtogroup dxgGlobals global declarations
//@{
//<#!@READ-ONLY-SECTION-END@!#>
//Start of 'chi_icn_PlfPlf global type' algorithm generated code

//End of 'chi_icn_PlfPlf global type' algorithm generated code
//<#!@READ-ONLY-SECTION-START@!#>
//@}

#endif // COFS_MODEL_CHI_ICN_PLFPLF_CHI_ICN_PLFPLF_GLOBAL_TYPE_DEFINITIONS

//<#!@READ-ONLY-SECTION-END@!#>