//<#!@READ-ONLY-SECTION-START@!#>
/*!
 * \class cfm_chi_icn
 * \brief Intel(R) CoFluent(TM) Studio - Intel Corporation
 * \details Simulation model of chi_icn_PlfPlf generated by C++ Generator for SystemC/TLM2
 */

#ifndef COFS_MODEL_CHI_ICN_PLFPLF_CHI_ICN
#define COFS_MODEL_CHI_ICN_PLFPLF_CHI_ICN

#include "cofluent.h"
/*Start of 'Inherited classes header' from CHI_ICN property generated code*/
#include "iconnect-chi.h"
/*End of 'Inherited classes header' from CHI_ICN property generated code*/
//<#!@READ-ONLY-SECTION-END@!#>
//Start of 'CHI_ICN includes' algorithm generated code
#define comma ,
//End of 'CHI_ICN includes' algorithm generated code
//<#!@READ-ONLY-SECTION-START@!#>

///    \defgroup dxgCHI_ICN Function CHI_ICN
//@{
///        \page dxpCHI_ICN
//@{
///    \brief CHI_ICN function model.
class cfm_chi_icn:
/*Start of 'Inherited classes declaration' from CHI_ICN property generated code*/
public iconnect_chi<20 comma 10 comma 2 comma 0>
/*End of 'Inherited classes declaration' from CHI_ICN property generated code*/
{
public:
	/// constructor
	cfm_chi_icn(sc_core::sc_module_name name);

	/// destructor
	virtual ~cfm_chi_icn(void);

	/// before arbitration callback
	void itc_bus_CHI_ICN_cb_before_arbitration(
			const tlm::tlm_generic_payload & _trans);

	/// after arbitration callback
	void itc_bus_CHI_ICN_cb_after_arbitration(
			const tlm::tlm_generic_payload & _trans);

	/// before transfer callback
	void itc_bus_CHI_ICN_cb_before_transfer(
			const tlm::tlm_generic_payload & _trans);

	/// after transfer callback
	void itc_bus_CHI_ICN_cb_after_transfer(
			const tlm::tlm_generic_payload & _trans);

protected:
	/// initialize definitions
	void cb_init_local_vars(void);

	/// \name user-defined local declarations
	//<#!@READ-ONLY-SECTION-END@!#>
	//Start of 'CHI_ICN local declarations' algorithm generated code

	//End of 'CHI_ICN local declarations' algorithm generated code
	//<#!@READ-ONLY-SECTION-START@!#>

};

//@}
//@}
#endif // COFS_MODEL_CHI_ICN_PLFPLF_CHI_ICN

//<#!@READ-ONLY-SECTION-END@!#>