//<#!@READ-ONLY-SECTION-START@!#>
/// \mainpage chi_icn_PlfPlf
///
/// Source code generated by Intel CoFluent C++ Generator for SystemC/TLM2 for:
///
/// project: chi_icn_PlfPlf
///
/// \section dxsGlobals Globals
///
///    - \subpage dxpGlobals "Global declarations/initializations"
///
///    - \subpage dxpRelTypes "Relation Datatypes"
///
///    - \subpage dxpDPTypes "Design Parameter Types"
///
///    - \subpage dxpUserCallbacks "User-defined callback functions"
///
/// \section dxsModules Design modules
///
///    - \subpage dxpchi_icn_PlfPlf "Application chi_icn_PlfPlf"
///
///    - \subpage dxpchi_icn_PlfPlf "Function chi_icn_PlfPlf"
///
///    - \subpage dxptg_rnf "Function tg_rnf"
///
///    - \subpage dxpMI "Function MI"
///
///    - \subpage dxpmem_sn "Function mem_sn"
///
///    - \subpage dxpSI "Function SI"
///
///
/// Intel(R) CoFluent(TM) Studio - Intel Corporation
/// Version: x.y.z Dev - Build id: x.y.z-dev
/// C++ Modeling Library for SystemC/TLM2 (SCL)
///

#ifndef COFS_MODEL_CHI_ICN_PLFPLF_CHI_ICN_PLFPLF_GLOBAL_DEFINITIONS
#define COFS_MODEL_CHI_ICN_PLFPLF_CHI_ICN_PLFPLF_GLOBAL_DEFINITIONS

/// global includes start
#include "cfm_chi_icn_plfplf_global_types.h"
#include "cofluent.h"

/// global includes end
#ifndef COFS_MODEL_APPLICATION_LEVEL
#define COFS_MODEL_APPLICATION_LEVEL
#endif

/// \defgroup dxgGlobals global declarations
//@{
///		\page dxpGlobals
//@{
//<#!@READ-ONLY-SECTION-END@!#>
//Start of 'chi_icn_PlfPlf global declarations' algorithm generated code

//End of 'chi_icn_PlfPlf global declarations' algorithm generated code
//<#!@READ-ONLY-SECTION-START@!#>
//@}
//@}

#endif // COFS_MODEL_CHI_ICN_PLFPLF_CHI_ICN_PLFPLF_GLOBAL_DEFINITIONS

//<#!@READ-ONLY-SECTION-END@!#>