//<#!@READ-ONLY-SECTION-START@!#>
/*
 * \brief Intel(R) CoFluent(TM) Studio - Intel Corporation
 * \details Simulation model of chi_icn_plf_packupPlf generated by C++ Generator for SystemC/TLM2
 */

#include "cfm_chi_icn_plf_packupplf_top.h"
using namespace std;
using namespace sc_core;
using namespace cf_dt;
using namespace cf_pk;
using namespace cf_core;

#ifdef COFS_MODEL_TYPE_APPLICATION_MODELING
int sc_main(int argc, char *argv[])
{

	// chi_icn_plf_packupPlf instantiation
	cfm_chi_icn_plf_packupplf* cfmi_chi_icn_plf_packupPlf = new cfm_chi_icn_plf_packupplf("chi_icn_plf_packupPlf");

	// start simulation
	cf_start();

	// shutdown simulator
	cf_stop();
	delete cfmi_chi_icn_plf_packupPlf;

	return EXIT_SUCCESS;
}
#endif // COFS_MODEL_TYPE_ARCHITECTURE_MODELING

//<#!@READ-ONLY-SECTION-END@!#>