//<#!@READ-ONLY-SECTION-START@!#>
/*
 * \class cfm_chi_icn
 * \brief Intel(R) CoFluent(TM) Studio - Intel Corporation
 * \details Simulation model of chi_icn_PlfPlf generated by C++ Generator for SystemC/TLM2
 */
#include "cfm_chi_icn.h"
using namespace std;
using namespace sc_core;
using namespace cf_dt;
using namespace cf_pk;
using namespace cf_core;
//<#!@READ-ONLY-SECTION-END@!#>
//Start of 'CHI_ICN definitions' algorithm generated code

//End of 'CHI_ICN definitions' algorithm generated code
//<#!@READ-ONLY-SECTION-START@!#>

/// \name constructor
//@{
cfm_chi_icn::cfm_chi_icn(sc_core::sc_module_name name) :
		/*Start of 'Inherited classes call' from CHI_ICN's model property generated code*/
		iconnect_chi(name)
/*End of 'Inherited classes call' from CHI_ICN's model property generated code*/
{
	//cf_bus::init();

	//cf_bus::elab_end();
}
//@}

/// \name destructor
//@{
cfm_chi_icn::~cfm_chi_icn(void) {
	//<#!@READ-ONLY-SECTION-END@!#>
	//Start of 'CHI_ICN destructor' algorithm generated code

	//End of 'CHI_ICN destructor' algorithm generated code
	//<#!@READ-ONLY-SECTION-START@!#>
}
//@}

/// \name initialize definitions
//@{
void cfm_chi_icn::cb_init_local_vars(void) {
	//<#!@READ-ONLY-SECTION-END@!#>
	//Start of 'CHI_ICN initializations' algorithm generated code

	//End of 'CHI_ICN initializations' algorithm generated code
	//<#!@READ-ONLY-SECTION-START@!#>
}
//@}

/// \name before arbitration callback
//@{
void cfm_chi_icn::itc_bus_CHI_ICN_cb_before_arbitration(
		const tlm::tlm_generic_payload & _trans) {
	//<#!@READ-ONLY-SECTION-END@!#>
	//Start of 'CHI_ICN Before Arbitration' algorithm generated code

	//End of 'CHI_ICN Before Arbitration' algorithm generated code
	//<#!@READ-ONLY-SECTION-START@!#>
}
//@}
/// \name after arbitration callback
//@{
void cfm_chi_icn::itc_bus_CHI_ICN_cb_after_arbitration(
		const tlm::tlm_generic_payload & _trans) {
	//<#!@READ-ONLY-SECTION-END@!#>
	//Start of 'CHI_ICN After Arbitration' algorithm generated code

	//End of 'CHI_ICN After Arbitration' algorithm generated code
	//<#!@READ-ONLY-SECTION-START@!#>
}
//@}
/// \name before transfer callback
//@{
void cfm_chi_icn::itc_bus_CHI_ICN_cb_before_transfer(
		const tlm::tlm_generic_payload & _trans) {
	//<#!@READ-ONLY-SECTION-END@!#>
	//Start of 'CHI_ICN Before Transfer' algorithm generated code

	//End of 'CHI_ICN Before Transfer' algorithm generated code
	//<#!@READ-ONLY-SECTION-START@!#>
}
//@}

/// \name after transfer callback
//@{
void cfm_chi_icn::itc_bus_CHI_ICN_cb_after_transfer(
		const tlm::tlm_generic_payload & _trans) {
	//<#!@READ-ONLY-SECTION-END@!#>
	//Start of 'CHI_ICN After Transfer' algorithm generated code

	//End of 'CHI_ICN After Transfer' algorithm generated code
	//<#!@READ-ONLY-SECTION-START@!#>
}
//@}


//<#!@READ-ONLY-SECTION-END@!#>