//<#!@READ-ONLY-SECTION-START@!#>
/*
 * \class cfm_mem_sn
 * \brief Intel(R) CoFluent(TM) Studio - Intel Corporation
 * \details Simulation model of chi_icn_PlfPlf generated by C++ Generator for SystemC/TLM2
 */
/// Model Source includes start
#include "cfm_mem_sn.h"
/// Model Source includes end
using namespace std;
using namespace sc_core;
using namespace cf_dt;
using namespace cf_pk;
using namespace cf_core;

//<#!@READ-ONLY-SECTION-END@!#>
//Start of 'mem_sn definitions' algorithm generated code

//End of 'mem_sn definitions' algorithm generated code
//<#!@READ-ONLY-SECTION-START@!#>

/// \name constructor
//@{
cfm_mem_sn::cfm_mem_sn(sc_core::sc_module_name name) :
		/*Start of 'Inherited classes call' from mem_sn's model property generated code*/
		SlaveNode_F(name)
/*End of 'Inherited classes call' from mem_sn's model property generated code*/
/*, p_bus_CHI_ICN("p_bus_CHI_ICN")*/
{
	cf_processor::init();

	/*SI = new cfm_mem_sn_si
	 ("SI");*/

	// connections
	//CHI_ICN is not streaming connection 
	/*p_bus_CHI_ICN
	 (SI->p_target_socket);
	 */

	//<#!@READ-ONLY-SECTION-END@!#>
	//Start of 'mem_sn constructor' algorithm generated code
	//End of 'mem_sn constructor' algorithm generated code
	//<#!@READ-ONLY-SECTION-START@!#>

	cf_processor::elab_end();
}
//@}

/// \name destructor
//@{
cfm_mem_sn::~cfm_mem_sn(void) {
	//<#!@READ-ONLY-SECTION-END@!#>
	//Start of 'mem_sn destructor' algorithm generated code

	//End of 'mem_sn destructor' algorithm generated code
	//<#!@READ-ONLY-SECTION-START@!#>
//delete SI;
}
//@}

/// \name pre-elaboration section
//@{
void cfm_mem_sn::cb_before_elaboration(void) {
	//<#!@READ-ONLY-SECTION-END@!#>
	//Start of 'mem_sn pre elaboration' algorithm generated code

	//End of 'mem_sn pre elaboration' algorithm generated code
	//<#!@READ-ONLY-SECTION-START@!#>
}
//@}

/// \name initialize attributes
//@{
void cfm_mem_sn::cb_init_attributes() {

// initialize processor attributes
	cfa_speed_up_ratio.init(cf_factor(1));
	cfa_cost.init(cf_cost(1, CF_USD));
	cfa_available_memory.init(cf_data_size(1, CF_MBYTE));
	cfa_static_load.init(cf_resource_load(0, CF_PERCENT));

	return;
}
//@}

/// \name initialize definitions
//@{
void cfm_mem_sn::cb_init_local_vars(void) {
	//<#!@READ-ONLY-SECTION-END@!#>
	//Start of 'mem_sn initializations' algorithm generated code

	//End of 'mem_sn initializations' algorithm generated code
	//<#!@READ-ONLY-SECTION-START@!#>
}
//@}

/// \name after active callback
//@{
void cfm_mem_sn::itc_proc_mem_sn_cb_after_active() {
	//<#!@READ-ONLY-SECTION-END@!#>
	//Start of 'mem_sn After Active' algorithm generated code

	//End of 'mem_sn After Active' algorithm generated code
	//<#!@READ-ONLY-SECTION-START@!#>
}

/// \name after inactive callback
//@{
void cfm_mem_sn::itc_proc_mem_sn_cb_after_inactive() {
	//<#!@READ-ONLY-SECTION-END@!#>
	//Start of 'mem_sn After Inactive' algorithm generated code

	//End of 'mem_sn After Inactive' algorithm generated code
	//<#!@READ-ONLY-SECTION-START@!#>
}


//<#!@READ-ONLY-SECTION-END@!#>