//<#!@READ-ONLY-SECTION-START@!#>
/*
 * \class cfm_bridge_rn_cache_chi
 * \brief Intel(R) CoFluent(TM) Studio - Intel Corporation
 * \details Simulation model of chi_icn_SysSys generated by C++ Generator for SystemC/TLM2
 */
/// Model Source includes start
#include "cfm_bridge_rn_cache_chi.h"
/// Model Source includes end
using namespace std;
using namespace sc_core;
using namespace cf_dt;
using namespace cf_pk;
using namespace cf_core;

//<#!@READ-ONLY-SECTION-END@!#>
//Start of 'cache_chi definitions' algorithm generated code

//End of 'cache_chi definitions' algorithm generated code
//<#!@READ-ONLY-SECTION-START@!#>

/// \name constructor
//@{
cfm_bridge_rn_cache_chi::cfm_bridge_rn_cache_chi(sc_core::sc_module_name name) :
		cf_master_interface(name) {
	cf_master_interface::init();

	//<#!@READ-ONLY-SECTION-END@!#>
	//Start of 'cache_chi constructor' algorithm generated code

	//End of 'cache_chi constructor' algorithm generated code
	//<#!@READ-ONLY-SECTION-START@!#>

	cf_master_interface::elab_end();
}
//@}

/// \name destructor
//@{
cfm_bridge_rn_cache_chi::~cfm_bridge_rn_cache_chi(void) {
	//<#!@READ-ONLY-SECTION-END@!#>
	//Start of 'cache_chi destructor' algorithm generated code

	//End of 'cache_chi destructor' algorithm generated code
	//<#!@READ-ONLY-SECTION-START@!#>
}
//@}

/// \name pre-elaboration section
//@{
void cfm_bridge_rn_cache_chi::cb_before_elaboration(void) {
	//<#!@READ-ONLY-SECTION-END@!#>
	//Start of 'cache_chi pre elaboration' algorithm generated code

	//End of 'cache_chi pre elaboration' algorithm generated code
	//<#!@READ-ONLY-SECTION-START@!#>
}
//@}

/// \name initialize attributes
//@{
void cfm_bridge_rn_cache_chi::cb_init_attributes() {

	cfa_buffer_policy.init(CF_IFC_BUFFER_POLICY_FIFO);
	cfa_buffer_capacity.init((cf_count) 1);
	cfa_available_memory.init(cf_data_size(1, CF_MBYTE));
	cfa_buffer_read_time.init(cf_expr_duration(1, CF_NS));
	cfa_buffer_write_time.init(cf_expr_duration(1, CF_NS));
	cfa_dynamic_power.init(cf_power(0, CF_UW));
	cfa_cost.init(cf_cost(0, CF_USD));
	cfa_dynamic_load.init(cf_resource_load(100, CF_PERCENT));
	cfa_concurrency.init((cf_nonzero_count) 1);

	return;
}
//@}

/// \name initialize definitions
//@{
void cfm_bridge_rn_cache_chi::cb_init_local_vars(void) {
	//<#!@READ-ONLY-SECTION-END@!#>
	//Start of 'cache_chi initializations' algorithm generated code

	//End of 'cache_chi initializations' algorithm generated code
	//<#!@READ-ONLY-SECTION-START@!#>
}
//@}

/// \name Overload function for interface before write component
//@{
void cfm_bridge_rn_cache_chi::itc_cb_before_write_component(
		const cf_core::cf_payload_b & _trans) {
	//<#!@READ-ONLY-SECTION-END@!#>
	//Start of 'cache_chi Before Write Component' algorithm generated code

	//End of 'cache_chi Before Write Component' algorithm generated code
	//<#!@READ-ONLY-SECTION-START@!#>
}
//@}
/// \name Overload function for interface before write interconnect
//@{
void cfm_bridge_rn_cache_chi::itc_cb_before_write_interconnect(
		const tlm::tlm_generic_payload & _trans) {
	//<#!@READ-ONLY-SECTION-END@!#>
	//Start of 'cache_chi Before Write Interconnect' algorithm generated code

	//End of 'cache_chi Before Write Interconnect' algorithm generated code
	//<#!@READ-ONLY-SECTION-START@!#>
}
//@}
/// \name Overload function for interface after write component
//@{
void cfm_bridge_rn_cache_chi::itc_cb_after_write_component(
		const cf_core::cf_payload_b & _trans) {
	//<#!@READ-ONLY-SECTION-END@!#>
	//Start of 'cache_chi After Write Component' algorithm generated code

	//End of 'cache_chi After Write Component' algorithm generated code
	//<#!@READ-ONLY-SECTION-START@!#>
}
//@}
/// \name Overload function for interface after write interconnect
//@{
void cfm_bridge_rn_cache_chi::itc_cb_after_write_interconnect(
		const tlm::tlm_generic_payload & _trans) {
	//<#!@READ-ONLY-SECTION-END@!#>
	//Start of 'cache_chi After Write Interconnect' algorithm generated code

	//End of 'cache_chi After Write Interconnect' algorithm generated code
	//<#!@READ-ONLY-SECTION-START@!#>
}
//@}
/// \name Overload function for interface before read component
//@{
void cfm_bridge_rn_cache_chi::itc_cb_before_read_component(
		const cf_core::cf_payload_b & _trans) {
	//<#!@READ-ONLY-SECTION-END@!#>
	//Start of 'cache_chi Before Read Component' algorithm generated code

	//End of 'cache_chi Before Read Component' algorithm generated code
	//<#!@READ-ONLY-SECTION-START@!#>
}
//@}
/// \name Overload function for interface before read interconnect
//@{
void cfm_bridge_rn_cache_chi::itc_cb_before_read_interconnect(
		const tlm::tlm_generic_payload & _trans) {
	//<#!@READ-ONLY-SECTION-END@!#>
	//Start of 'cache_chi Before Read Interconnect' algorithm generated code

	//End of 'cache_chi Before Read Interconnect' algorithm generated code
	//<#!@READ-ONLY-SECTION-START@!#>
}
//@}
/// \name Overload function for interface after read component
//@{
void cfm_bridge_rn_cache_chi::itc_cb_after_read_component(
		const cf_core::cf_payload_b & _trans) {
	//<#!@READ-ONLY-SECTION-END@!#>
	//Start of 'cache_chi After Read Component' algorithm generated code

	//End of 'cache_chi After Read Component' algorithm generated code
	//<#!@READ-ONLY-SECTION-START@!#>
}
//@}
/// \name Overload function for interface after read interconnect
//@{
void cfm_bridge_rn_cache_chi::itc_cb_after_read_interconnect(
		const tlm::tlm_generic_payload & _trans) {
	//<#!@READ-ONLY-SECTION-END@!#>
	//Start of 'cache_chi After Read Interconnect' algorithm generated code

	//End of 'cache_chi After Read Interconnect' algorithm generated code
	//<#!@READ-ONLY-SECTION-START@!#>
}
//@}


//<#!@READ-ONLY-SECTION-END@!#>