//<#!@READ-ONLY-SECTION-START@!#>
/*
 * \class cfm_tg_rnf_tlm
 * \brief Intel(R) CoFluent(TM) Studio - Intel Corporation
 * \details Simulation model of chi_icn_sysSys generated by C++ Generator for SystemC/TLM2
 */
/// Model Source includes start
#include "cfm_tg_rnf_tlm.h"
/// Model Source includes end
using namespace std;
using namespace sc_core;
using namespace cf_dt;
using namespace cf_pk;
using namespace cf_core;

//<#!@READ-ONLY-SECTION-END@!#>
//Start of 'tg_rnf_tlm definitions' algorithm generated code

//End of 'tg_rnf_tlm definitions' algorithm generated code
//<#!@READ-ONLY-SECTION-START@!#>

/// \name constructor
//@{
cfm_tg_rnf_tlm::cfm_tg_rnf_tlm(sc_core::sc_module_name name) :
		/*Start of 'Inherited classes call' from tg_rnf_tlm's model property generated code*/
		rnf_subsys(name)
/*End of 'Inherited classes call' from tg_rnf_tlm's model property generated code*/
/*, p_bus_CHI_ICN_TLM("p_bus_CHI_ICN_TLM")*/
{
	cf_processor::init();
	/*rnf_tlm = new cfm_tg_rnf_tlm_rnf_tlm
	 ("rnf_tlm");*/

	// connections
	//skip bind bus_CHI_ICN_TLM with rnf_tlm as already binded at tg_rnf_tlm external

	//<#!@READ-ONLY-SECTION-END@!#>
	//Start of 'tg_rnf_tlm constructor' algorithm generated code
	//End of 'tg_rnf_tlm constructor' algorithm generated code
	//<#!@READ-ONLY-SECTION-START@!#>

	cf_processor::elab_end();
}
//@}

/// \name destructor
//@{
cfm_tg_rnf_tlm::~cfm_tg_rnf_tlm(void) {
	//<#!@READ-ONLY-SECTION-END@!#>
	//Start of 'tg_rnf_tlm destructor' algorithm generated code

	//End of 'tg_rnf_tlm destructor' algorithm generated code
	//<#!@READ-ONLY-SECTION-START@!#>
	delete rnf_tlm;
}
//@}

/// \name pre-elaboration section
//@{
void cfm_tg_rnf_tlm::cb_before_elaboration(void) {
	//<#!@READ-ONLY-SECTION-END@!#>
	//Start of 'tg_rnf_tlm pre elaboration' algorithm generated code

	//End of 'tg_rnf_tlm pre elaboration' algorithm generated code
	//<#!@READ-ONLY-SECTION-START@!#>
}
//@}

/// \name initialize attributes
//@{
void cfm_tg_rnf_tlm::cb_init_attributes() {

// initialize processor attributes
	cfa_speed_up_ratio.init(cf_factor(1));
	cfa_cost.init(cf_cost(1, CF_USD));
	cfa_available_memory.init(cf_data_size(1, CF_MBYTE));
	cfa_static_load.init(cf_resource_load(0, CF_PERCENT));

	return;
}
//@}

/// \name initialize definitions
//@{
void cfm_tg_rnf_tlm::cb_init_local_vars(void) {
	//<#!@READ-ONLY-SECTION-END@!#>
	//Start of 'tg_rnf_tlm initializations' algorithm generated code

	//End of 'tg_rnf_tlm initializations' algorithm generated code
	//<#!@READ-ONLY-SECTION-START@!#>
}
//@}

/// \name after active callback
//@{
void cfm_tg_rnf_tlm::itc_proc_tg_rnf_tlm_cb_after_active() {
	//<#!@READ-ONLY-SECTION-END@!#>
	//Start of 'tg_rnf_tlm After Active' algorithm generated code

	//End of 'tg_rnf_tlm After Active' algorithm generated code
	//<#!@READ-ONLY-SECTION-START@!#>
}

/// \name after inactive callback
//@{
void cfm_tg_rnf_tlm::itc_proc_tg_rnf_tlm_cb_after_inactive() {
	//<#!@READ-ONLY-SECTION-END@!#>
	//Start of 'tg_rnf_tlm After Inactive' algorithm generated code

	//End of 'tg_rnf_tlm After Inactive' algorithm generated code
	//<#!@READ-ONLY-SECTION-START@!#>
}


//<#!@READ-ONLY-SECTION-END@!#>