//<#!@READ-ONLY-SECTION-START@!#>
/*
 * \class cfm_connector_st
 * \brief Intel(R) CoFluent(TM) Studio - Intel Corporation
 * \details Simulation model of chi_icn_sysSys generated by C++ Generator for SystemC/TLM2
 */
#include "cfm_connector_st.h"
using namespace std;
using namespace sc_core;
using namespace cf_dt;
using namespace cf_pk;
using namespace cf_core;
//<#!@READ-ONLY-SECTION-END@!#>
//Start of 'connector_st definitions' algorithm generated code

//End of 'connector_st definitions' algorithm generated code
//<#!@READ-ONLY-SECTION-START@!#>

/// \name constructor
//@{
cfm_connector_st::cfm_connector_st(sc_core::sc_module_name name) :
		/*Start of 'Inherited classes call' from connector_st's model property generated code*/
		empty()
/*End of 'Inherited classes call' from connector_st's model property generated code*/
{
	//cf_bus::init();
	//cf_bus::elab_end();
}
//@}

/// \name destructor
//@{
cfm_connector_st::~cfm_connector_st(void) {
	//<#!@READ-ONLY-SECTION-END@!#>
	//Start of 'connector_st destructor' algorithm generated code

	//End of 'connector_st destructor' algorithm generated code
	//<#!@READ-ONLY-SECTION-START@!#>
}
//@}

/// \name initialize definitions
//@{
void cfm_connector_st::cb_init_local_vars(void) {
	//<#!@READ-ONLY-SECTION-END@!#>
	//Start of 'connector_st initializations' algorithm generated code

	//End of 'connector_st initializations' algorithm generated code
	//<#!@READ-ONLY-SECTION-START@!#>
}
//@}

/// \name before arbitration callback
//@{
void cfm_connector_st::itc_bus_connector_st_cb_before_arbitration(
		const tlm::tlm_generic_payload & _trans) {
	//<#!@READ-ONLY-SECTION-END@!#>
	//Start of 'connector_st Before Arbitration' algorithm generated code

	//End of 'connector_st Before Arbitration' algorithm generated code
	//<#!@READ-ONLY-SECTION-START@!#>
}
//@}
/// \name after arbitration callback
//@{
void cfm_connector_st::itc_bus_connector_st_cb_after_arbitration(
		const tlm::tlm_generic_payload & _trans) {
	//<#!@READ-ONLY-SECTION-END@!#>
	//Start of 'connector_st After Arbitration' algorithm generated code

	//End of 'connector_st After Arbitration' algorithm generated code
	//<#!@READ-ONLY-SECTION-START@!#>
}
//@}
/// \name before transfer callback
//@{
void cfm_connector_st::itc_bus_connector_st_cb_before_transfer(
		const tlm::tlm_generic_payload & _trans) {
	//<#!@READ-ONLY-SECTION-END@!#>
	//Start of 'connector_st Before Transfer' algorithm generated code

	//End of 'connector_st Before Transfer' algorithm generated code
	//<#!@READ-ONLY-SECTION-START@!#>
}
//@}

/// \name after transfer callback
//@{
void cfm_connector_st::itc_bus_connector_st_cb_after_transfer(
		const tlm::tlm_generic_payload & _trans) {
	//<#!@READ-ONLY-SECTION-END@!#>
	//Start of 'connector_st After Transfer' algorithm generated code

	//End of 'connector_st After Transfer' algorithm generated code
	//<#!@READ-ONLY-SECTION-START@!#>
}
//@}


//<#!@READ-ONLY-SECTION-END@!#>